name: generate-snake-game-from-github-contribution-grid
on:	
  schedule:	
      # every 6 hours	
    - cron: "0 */6 * * *"
# This command allows us to run the Action automatically from the Actions tab.	
  workflow_dispatch:	

# The sequence of runs in this workflow:	
jobs:	
  # This workflow contains a single job called "build"	
  build:	
    # The type of runner that the job will run on	
    runs-on: ubuntu-latest	

    # Steps represent a sequence of tasks that will be executed as part of the job	
    steps:
    - uses: actions/checkout@v2
    - name: Run Snakemake
      uses: Platane/snk@v2.2.0
      with:
        snakefile: Snakefile
        use-conda: true
        conda-prefix: /opt/conda
        config: '{"input_file": "data/input.csv"}'
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: results/

